#!/usr/bin/env php
<?php

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

require_once __DIR__ . '/vendor/autoload.php';

$kernel = new \PhpDeployer\Console\Kernel(__DIR__);

$status = $kernel->run($_SERVER['argv'] ?? []);

exit($status->value);
