services:
  php:
    container_name: pms-deployer
    restart: unless-stopped
    build:
      context: ./docker/php
      args:
        - GROUP_ID=${DOCKER_GROUP_ID}
        - USER_ID=${DOCKER_USER_ID}
    working_dir: /app
    volumes:
      - ./:/app
